# Schema for the configuration files of the autocode_test module.
autocode_test.settings:
  type: config_object
  label: 'autocode_test settings'
  mapping:
    example:
      type: string
      label: 'Example'
