name: nia-iadrp-coding-portal
recipe: drupal10
proxy:
  appserver:
    - nia-iadrp-coding-portal.lndo.site
  mailhog:
    - mail.nia-iadrp-coding-portal.lndo.site
  phpmysql:
    - phpmysql.nia-iadrp-coding-portal.lndo.site
config:
  webroot: ./web
  php: '8.1'
  composer_version: '2.2.12'
  via: apache:2.4
  database: mysql:5.7
  drush: ^11
  xdebug: false
  config:
    php: lando_config/php/php.ini
    database: lando_config/mysql/my.cnf
services:
  appserver:
    build:
      - composer install
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  phpmysql:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node
    ssl: true
    run: 
      - (cd /app/web/themes/custom/uswds_NIA;npm install @uswds/compile --save-dev)
      - (cd /app/web/themes/custom/uswds_NIA;npm install --save @uswds/uswds@latest)
      - (cd /app/web/themes/custom/uswds_NIA;npx gulp compile)
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
    dir: /app/web/themes/custom/uswds_NIA
  yarn:
    service: node
  npx:
    service: node
    dir: /app/web/themes/custom/uswds_NIA