name: nia-iadrp-coding-portal
recipe: drupal10
proxy:
  appserver:
    - nia-iadrp-coding-portal.lndo.site
  mailhog:
    - mail.nia-iadrp-coding-portal.lndo.site
config:
  webroot: ./web
  php: '8.1'
  composer_version: '2.2.12'
  via: apache:2.4
  database: mysql:5.7
  drush: ^11
  xdebug: false
  config:
    php: lando_config/php/php.ini
    database: lando_config/mysql/my.cnf
services:
  appserver:
    build:
      - composer install
  mailhog:
    type: mailhog
    hogfrom:
      - appserver