<?php

/**
 * @file
 * USWDS NIA.
 *
 * Place your custom PHP code in this file.
 */
/**
 * Implements hook_preprocess().
 */
function uswds_NIA_preprocess(&$variables) {
  // Set the path to the base theme.
  $variables['active_theme_path'] = base_path() . \Drupal::theme()->getActiveTheme()->getPath();
  $variables['uswds_images'] = $variables['active_theme_path'] . '/node_modules/@uswds/uswds/dist/img/';
}
